name: Decrypt and Unpack Python Payload

on:
  workflow_dispatch: # Cho phép bạn bấm nút chạy thủ công trên giao diện Web

jobs:
  unpack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install PyCryptodome
      run: |
        python -m pip install --upgrade pip
        pip install pycryptodome

    - name: Run Decryption Script
      run: |
        # Chạy file main.py đã sửa đổi để nó tự giải mã và xuất ra file decoded_payload.py
        python main.py
        
    - name: Upload Decrypted Artifact
      uses: actions/upload-artifact@v4
      with:
        name: decrypted-source-code
        path: decoded_payload.py
